pub const CREATE_NODE_PROJECT: &str =
    "CREATE NODE TABLE Project(id STRING, path STRING, PRIMARY KEY(id))";
pub const CREATE_NODE_SESSION: &str =
    "CREATE NODE TABLE Session(id STRING, harness STRING, started_at STRING, PRIMARY KEY(id))";
pub const CREATE_NODE_TURN: &str =
    "CREATE NODE TABLE Turn(id STRING, role STRING, PRIMARY KEY(id))";
pub const CREATE_NODE_MEMORY: &str =
    "CREATE NODE TABLE Memory(id STRING, kind STRING, level INT64, PRIMARY KEY(id))";
pub const CREATE_NODE_CONFLICT: &str =
    "CREATE NODE TABLE Conflict(id STRING, explanation STRING, PRIMARY KEY(id))";
pub const CREATE_NODE_RECIPE: &str =
    "CREATE NODE TABLE Recipe(id STRING, name STRING, PRIMARY KEY(id))";

pub const CREATE_REL_IN_PROJECT: &str = "CREATE REL TABLE IN_PROJECT(FROM Session TO Project)";
pub const CREATE_REL_IN_SESSION: &str = "CREATE REL TABLE IN_SESSION(FROM Turn TO Session)";
pub const CREATE_REL_RECALLS: &str = "CREATE REL TABLE RECALLS(FROM Turn TO Memory)";
pub const CREATE_REL_SOURCE_FOR: &str = "CREATE REL TABLE SOURCE_FOR(FROM Turn TO Memory)";
pub const CREATE_REL_CONFLICTS_WITH: &str =
    "CREATE REL TABLE CONFLICTS_WITH(FROM Conflict TO Memory)";
pub const CREATE_REL_PART_OF_RECIPE: &str =
    "CREATE REL TABLE PART_OF_RECIPE(FROM Session TO Recipe)";
pub const CREATE_REL_SYNTHESIZED_FROM: &str =
    "CREATE REL TABLE SYNTHESIZED_FROM(FROM Memory TO Memory)";

pub const TABLES: &[(&str, &str)] = &[
    ("Project", CREATE_NODE_PROJECT),
    ("Session", CREATE_NODE_SESSION),
    ("Turn", CREATE_NODE_TURN),
    ("Memory", CREATE_NODE_MEMORY),
    ("Conflict", CREATE_NODE_CONFLICT),
    ("Recipe", CREATE_NODE_RECIPE),
    ("IN_PROJECT", CREATE_REL_IN_PROJECT),
    ("IN_SESSION", CREATE_REL_IN_SESSION),
    ("RECALLS", CREATE_REL_RECALLS),
    ("SOURCE_FOR", CREATE_REL_SOURCE_FOR),
    ("CONFLICTS_WITH", CREATE_REL_CONFLICTS_WITH),
    ("PART_OF_RECIPE", CREATE_REL_PART_OF_RECIPE),
    ("SYNTHESIZED_FROM", CREATE_REL_SYNTHESIZED_FROM),
];
